package hello;

import javax.mail.internet.AddressException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.User;
import hello.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
//	@GetMapping(path="/add") // Map ONLY GET Requests
//	public @ResponseBody String addNewUser (@RequestParam String name
//			, @RequestParam String email) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//		
//		User n = new User();
//		n.setName(name);
//		n.setEmail(email);
//		userRepository.save(n);
//		return "Saved";
//	}
	
//	@GetMapping(path="/all")
//	public @ResponseBody Iterable<User> getAllUsers() {
//		// This returns a JSON or XML with the users
//		return userRepository.findAll();
//	}
	@GetMapping(path="/addUser")
	public @ResponseBody String addUser(@RequestParam String name, @RequestParam String location, @RequestParam String phone, @RequestParam String emailId) {
		System.out.println("Add user");
		User user = new User(name,location,phone,emailId);
		userRepository.save(user);
		return "Saved";
	}
	
	@RequestMapping(path="/sendNotification")
	public @ResponseBody String sendNotification(@RequestParam int id) {
		try {
			System.out.println("i am here"+id);
			User user = userRepository.findOne(id);
			System.out.println(user.getId()+"===="+user.getName());
		
			SendEmail.sendEmail(user.getEmail(), "pravari1@binghamton.edu", "Visitor at your home", "Visitor at your "+user.getLocation());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return "Saved";
	}
}
